# Network Settings
network:
  host_ip: 0.0.0.0
  api_port: 8001

# API settings
api:
  domain_name: "api.pxecloud.tk"
  protocol: "https"

# RethinkDB settings
rethinkdb:
  host: 0.0.0.0
  port: 28015
  db_name: pxecloud

# Storage settings
storage:
  # TODO: Image limit size
  image_limit_size:
  path: "./images"

ipxe:
  # For a complete list of keymaps, please check https://ipxe.org/buildcfg/keyboard_map
  keymap: es